site_name: LeetCode Wiki
site_url: https://doocs.github.io/leetcode
site_description: 多种编程语言实现 LeetCode、《剑指 Offer（第 2 版）》、《程序员面试金典（第 6 版）》题解
site_author: yanglbme
site_dir: site
docs_dir: docs
repo_name: doocs/leetcode
repo_url: https://github.com/doocs/leetcode
copyright: Copyright &copy; 2024 <a href="https://github.com/doocs">Doocs</a><br><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">知识共享 版权归属-相同方式共享 4.0 国际 公共许可证</a>

theme:
  favicon: favicon.ico
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags:
      tags_file: tags.md
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true

hooks:
  - hooks/edit_url.py
  - hooks/tags.py
  - hooks/committer.py
  - hooks/fix_markdown_block.py

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yanglbme
    - icon: simple/gitee
      link: https://gitee.com/yanglbme
    - icon: simple/leetcode
      link: https://leetcode.cn/u/lcbin/
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@yanglibin.info
  alternate:
    - name: English
      link: /leetcode/en/
      lang: en
    - name: 中文
      link: /leetcode/
      lang: zh

nav:
  - 首页: index.md
  - LeetCode 全解:
    - 1. 两数之和: lc/1.md
    - 2. 两数相加: lc/2.md
  - 剑指 Offer:
    - 3. 数组中重复的数字: lcof/3.md
    - 4. 二维数组中的查找: lcof/4.md
    - 5. 替换空格: lcof/5.md
    - 6. 从尾到头打印链表: lcof/6.md
    - 7. 重建二叉树: lcof/7.md
    - 9. 用两个栈实现队列: lcof/9.md
    - 10.1. 斐波那契数列: lcof/10.1.md
    - 10.2. 青蛙跳台阶问题: lcof/10.2.md
    - 11. 旋转数组的最小数字: lcof/11.md
    - 12. 矩阵中的路径: lcof/12.md
    - 13. 机器人的运动范围: lcof/13.md
    - 14.1. 剪绳子: lcof/14.1.md
    - 14.2. 剪绳子 II: lcof/14.2.md
    - 15. 二进制中 1 的个数: lcof/15.md
    - 16. 数值的整数次方: lcof/16.md
    - 17. 打印从 1 到最大的 n 位数: lcof/17.md
    - 18. 删除链表的节点: lcof/18.md
    - 19. 正则表达式匹配: lcof/19.md
    - 20. 表示数值的字符串: lcof/20.md
    - 21. 调整数组顺序使奇数位于偶数前面: lcof/21.md
    - 22. 链表中倒数第 k 个节点: lcof/22.md
    - 24. 反转链表: lcof/24.md
    - 25. 合并两个排序的链表: lcof/25.md
    - 26. 树的子结构: lcof/26.md
    - 27. 二叉树的镜像: lcof/27.md
    - 28. 对称的二叉树: lcof/28.md
    - 29. 顺时针打印矩阵: lcof/29.md
    - 30. 包含 min 函数的栈: lcof/30.md
    - 31. 栈的压入、弹出序列: lcof/31.md
    - 32.1. 从上到下打印二叉树: lcof/32.1.md
    - 32.2. 从上到下打印二叉树 II: lcof/32.2.md
    - 32.3. 从上到下打印二叉树 III: lcof/32.3.md
    - 33. 二叉搜索树的后序遍历序列: lcof/33.md
    - 34. 二叉树中和为某一值的路径: lcof/34.md
    - 35. 复杂链表的复制: lcof/35.md
    - 36. 二叉搜索树与双向链表: lcof/36.md
    - 37. 序列化二叉树: lcof/37.md
    - 38. 字符串的排列: lcof/38.md
    - 39. 数组中出现次数超过一半的数字: lcof/39.md
    - 40. 最小的 k 个数: lcof/40.md
    - 41. 数据流中的中位数: lcof/41.md
    - 42. 连续子数组的最大和: lcof/42.md
    - 43. 1 ～ n 整数中 1 出现的次数: lcof/43.md
    - 44. 数字序列中某一位的数字: lcof/44.md
    - 45. 把数组排成最小的数: lcof/45.md
    - 46. 把数字翻译成字符串: lcof/46.md
    - 47. 礼物的最大价值: lcof/47.md
    - 48. 最长不含重复字符的子字符串: lcof/48.md
    - 49. 丑数: lcof/49.md
    - 50. 第一个只出现一次的字符: lcof/50.md
    - 51. 数组中的逆序对: lcof/51.md
    - 52. 两个链表的第一个公共节点: lcof/52.md
    - 53.1. 在排序数组中查找数字 I: lcof/53.1.md
    - 53.2.  ～ n-1 中缺失的数字: lcof/53.2.md
    - 54. 二叉搜索树的第 k 大节点: lcof/54.md
    - 55.1. 二叉树的深度: lcof/55.1.md
    - 55.2. 平衡二叉树: lcof/55.2.md
    - 56.1. 数组中数字出现的次数: lcof/56.1.md
    - 56.2. 数组中数字出现的次数 II: lcof/56.2.md
    - 57.2. 和为 s 的连续正数序列: lcof/57.2.md
    - 57. 和为 s 的两个数字: lcof/57.md
    - 58.1. 翻转单词顺序: lcof/58.1.md
    - 58.2. 左旋转字符串: lcof/58.2.md
    - 59.1. 滑动窗口的最大值: lcof/59.1.md
    - 59.2. 队列的最大值: lcof/59.2.md
    - 60. n 个骰子的点数: lcof/60.md
    - 61. 扑克牌中的顺子: lcof/61.md
    - 62. 圆圈中最后剩下的数字: lcof/62.md
    - 63. 股票的最大利润: lcof/63.md
    - 64. 求 1+2+…+n: lcof/64.md
    - 65. 不用加减乘除做加法: lcof/65.md
    - 66. 构建乘积数组: lcof/66.md
    - 67. 把字符串转换成整数: lcof/67.md
    - 68.1. 二叉搜索树的最近公共祖先: lcof/68.1.md
    - 68.2. 二叉树的最近公共祖先: lcof/68.2.md
  - 剑指 Offer（专项突破）:
    - 1. 整数除法: lcof2/1.md
    - 2. 二进制加法: lcof2/2.md
    - 3. 前 n 个数字二进制中 1 的个数: lcof2/3.md
    - 4. 只出现一次的数字: lcof2/4.md
    - 5. 单词长度的最大乘积: lcof2/5.md
    - 6. 排序数组中两个数字之和: lcof2/6.md
    - 7. 数组中和为 0 的三个数: lcof2/7.md
    - 8. 和大于等于 target 的最短子数组: lcof2/8.md
    - 9. 乘积小于 K 的子数组: lcof2/9.md
    - 10. 和为 k 的子数组: lcof2/10.md
    - 11.  和 1 个数相同的子数组: lcof2/11.md
    - 12. 左右两边子数组的和相等: lcof2/12.md
    - 13. 二维子矩阵的和: lcof2/13.md
    - 14. 字符串中的变位词: lcof2/14.md
    - 15. 字符串中的所有变位词: lcof2/15.md
    - 16. 不含重复字符的最长子字符串: lcof2/16.md
    - 17. 含有所有字符的最短字符串: lcof2/17.md
    - 18. 有效的回文: lcof2/18.md
    - 19. 最多删除一个字符得到回文: lcof2/19.md
    - 20. 回文子字符串的个数: lcof2/20.md
    - 21. 删除链表的倒数第 n 个结点: lcof2/21.md
    - 22. 链表中环的入口节点: lcof2/22.md
    - 23. 两个链表的第一个重合节点: lcof2/23.md
    - 24. 反转链表: lcof2/24.md
    - 25. 链表中的两数相加: lcof2/25.md
    - 26. 重排链表: lcof2/26.md
    - 27. 回文链表: lcof2/27.md
    - 28. 展平多级双向链表: lcof2/28.md
    - 29. 排序的循环链表: lcof2/29.md
    - 30. 插入、删除和随机访问都是 O(1) 的容器: lcof2/30.md
    - 31. 最近最少使用缓存: lcof2/31.md
    - 32. 有效的变位词: lcof2/32.md
    - 33. 变位词组: lcof2/33.md
    - 34. 外星语言是否排序: lcof2/34.md
    - 35. 最小时间差: lcof2/35.md
    - 36. 后缀表达式: lcof2/36.md
    - 37. 小行星碰撞: lcof2/37.md
    - 38. 每日温度: lcof2/38.md
    - 39. 直方图最大矩形面积: lcof2/39.md
    - 40. 矩阵中最大的矩形: lcof2/40.md
    - 41. 滑动窗口的平均值: lcof2/41.md
    - 42. 最近请求次数: lcof2/42.md
    - 43. 往完全二叉树添加节点: lcof2/43.md
    - 44. 二叉树每层的最大值: lcof2/44.md
    - 45. 二叉树最底层最左边的值: lcof2/45.md
    - 46. 二叉树的右侧视图: lcof2/46.md
    - 47. 二叉树剪枝: lcof2/47.md
    - 48. 序列化与反序列化二叉树: lcof2/48.md
    - 49. 从根节点到叶节点的路径数字之和: lcof2/49.md
    - 50. 向下的路径节点之和: lcof2/50.md
    - 51. 节点之和最大的路径: lcof2/51.md
    - 52. 展平二叉搜索树: lcof2/52.md
    - 53. 二叉搜索树中的中序后继: lcof2/53.md
    - 54. 所有大于等于节点的值之和: lcof2/54.md
    - 55. 二叉搜索树迭代器: lcof2/55.md
    - 56. 二叉搜索树中两个节点之和: lcof2/56.md
    - 57. 值和下标之差都在给定的范围内: lcof2/57.md
    - 58. 日程表: lcof2/58.md
    - 59. 数据流的第 K 大数值: lcof2/59.md
    - 60. 出现频率最高的 k 个数字: lcof2/60.md
    - 61. 和最小的 k 个数对: lcof2/61.md
    - 62. 实现前缀树: lcof2/62.md
    - 63. 替换单词: lcof2/63.md
    - 64. 神奇的字典: lcof2/64.md
    - 65. 最短的单词编码: lcof2/65.md
    - 66. 单词之和: lcof2/66.md
    - 67. 最大的异或: lcof2/67.md
    - 68. 查找插入位置: lcof2/68.md
    - 69. 山峰数组的顶部: lcof2/69.md
    - 70. 排序数组中只出现一次的数字: lcof2/70.md
    - 71. 按权重生成随机数: lcof2/71.md
    - 72. 求平方根: lcof2/72.md
    - 73. 狒狒吃香蕉: lcof2/73.md
    - 74. 合并区间: lcof2/74.md
    - 75. 数组相对排序: lcof2/75.md
    - 76. 数组中的第 k 大的数字: lcof2/76.md
    - 77. 链表排序: lcof2/77.md
    - 78. 合并排序链表: lcof2/78.md
    - 79. 所有子集: lcof2/79.md
    - 80. 含有 k 个元素的组合: lcof2/80.md
    - 81. 允许重复选择元素的组合: lcof2/81.md
    - 82. 含有重复元素集合的组合: lcof2/82.md
    - 83. 没有重复元素集合的全排列: lcof2/83.md
    - 84. 含有重复元素集合的全排列: lcof2/84.md
    - 85. 生成匹配的括号: lcof2/85.md
    - 86. 分割回文子字符串: lcof2/86.md
    - 87. 复原 IP: lcof2/87.md
    - 88. 爬楼梯的最少成本: lcof2/88.md
    - 89. 房屋偷盗: lcof2/89.md
    - 90. 环形房屋偷盗: lcof2/90.md
    - 91. 粉刷房子: lcof2/91.md
    - 92. 翻转字符: lcof2/92.md
    - 93. 最长斐波那契数列: lcof2/93.md
    - 94. 最少回文分割: lcof2/94.md
    - 95. 最长公共子序列: lcof2/95.md
    - 96. 字符串交织: lcof2/96.md
    - 97. 子序列的数目: lcof2/97.md
    - 98. 路径的数目: lcof2/98.md
    - 99. 最小路径之和: lcof2/99.md
    - 100. 三角形中最小路径之和: lcof2/100.md
    - 101. 分割等和子串: lcof2/101.md
    - 102. 加减的目标值: lcof2/102.md
    - 103. 最少的硬币数目: lcof2/103.md
    - 104. 排列的数目: lcof2/104.md
    - 105. 岛屿的最大面积: lcof2/105.md
    - 106. 二分图: lcof2/106.md
    - 107. 矩阵中的距离: lcof2/107.md
    - 108. 单词演变: lcof2/108.md
    - 109. 开密码锁: lcof2/109.md
    - 110. 所有路径: lcof2/110.md
    - 111. 计算除法: lcof2/111.md
    - 112. 最长递增路径: lcof2/112.md
    - 113. 课程顺序: lcof2/113.md
    - 114. 外星文字典: lcof2/114.md
    - 115. 重建序列: lcof2/115.md
    - 116. 朋友圈: lcof2/116.md
    - 117. 相似的字符串: lcof2/117.md
    - 118. 多余的边: lcof2/118.md
    - 119. 最长连续序列: lcof2/119.md
  - 程序员面试金典:
    - 1.1. 判定字符是否唯一: lcci/1.1.md
    - 1.2. 判定是否互为字符重排: lcci/1.2.md
    - 1.3. URL 化: lcci/1.3.md
    - 1.4. 回文排列: lcci/1.4.md
    - 1.5. 一次编辑: lcci/1.5.md
    - 1.6. 字符串压缩: lcci/1.6.md
    - 1.7. 旋转矩阵: lcci/1.7.md
    - 1.8. 零矩阵: lcci/1.8.md
    - 1.9. 字符串轮转: lcci/1.9.md
    - 2.1. 移除重复节点: lcci/2.1.md
    - 2.2. 返回倒数第 k 个节点: lcci/2.2.md
    - 2.3. 删除中间节点: lcci/2.3.md
    - 2.4. 分割链表: lcci/2.4.md
    - 2.5. 链表求和: lcci/2.5.md
    - 2.6. 回文链表: lcci/2.6.md
    - 2.7. 链表相交: lcci/2.7.md
    - 2.8. 环路检测: lcci/2.8.md
    - 3.1. 三合一: lcci/3.1.md
    - 3.2. 栈的最小值: lcci/3.2.md
    - 3.3. 堆盘子: lcci/3.3.md
    - 3.4. 化栈为队: lcci/3.4.md
    - 3.5. 栈排序: lcci/3.5.md
    - 3.6. 动物收容所: lcci/3.6.md
    - 4.1. 节点间通路: lcci/4.1.md
    - 4.2. 最小高度树: lcci/4.2.md
    - 4.3. 特定深度节点链表: lcci/4.3.md
    - 4.4. 检查平衡性: lcci/4.4.md
    - 4.5. 合法二叉搜索树: lcci/4.5.md
    - 4.6. 后继者: lcci/4.6.md
    - 4.8. 首个共同祖先: lcci/4.8.md
    - 4.9. 二叉搜索树序列: lcci/4.9.md
    - 4.10. 检查子树: lcci/4.10.md
    - 4.12. 求和路径: lcci/4.12.md
    - 5.1. 插入: lcci/5.1.md
    - 5.2. 二进制数转字符串: lcci/5.2.md
    - 5.3. 翻转数位: lcci/5.3.md
    - 5.4. 下一个数: lcci/5.4.md
    - 5.6. 整数转换: lcci/5.6.md
    - 5.7. 配对交换: lcci/5.7.md
    - 5.8. 绘制直线: lcci/5.8.md
    - 8.1. 三步问题: lcci/8.1.md
    - 8.2. 迷路的机器人: lcci/8.2.md
    - 8.3. 魔术索引: lcci/8.3.md
    - 8.4. 幂集: lcci/8.4.md
    - 8.5. 递归乘法: lcci/8.5.md
    - 8.6. 汉诺塔问题: lcci/8.6.md
    - 8.7. 无重复字符串的排列组合: lcci/8.7.md
    - 8.8. 有重复字符串的排列组合: lcci/8.8.md
    - 8.9. 括号: lcci/8.9.md
    - 8.10. 颜色填充: lcci/8.10.md
    - 8.11. 硬币: lcci/8.11.md
    - 8.12. 八皇后: lcci/8.12.md
    - 8.13. 堆箱子: lcci/8.13.md
    - 8.14. 布尔运算: lcci/8.14.md
    - 10.1. 合并排序的数组: lcci/10.1.md
    - 10.2. 变位词组: lcci/10.2.md
    - 10.3. 搜索旋转数组: lcci/10.3.md
    - 10.5. 稀疏数组搜索: lcci/10.5.md
    - 10.9. 排序矩阵查找: lcci/10.9.md
    - 10.10. 数字流的秩: lcci/10.10.md
    - 10.11. 峰与谷: lcci/10.11.md
    - 16.1. 交换数字: lcci/16.1.md
    - 16.2. 单词频率: lcci/16.2.md
    - 16.3. 交点: lcci/16.3.md
    - 16.4. 井字游戏: lcci/16.4.md
    - 16.5. 阶乘尾数: lcci/16.5.md
    - 16.6. 最小差: lcci/16.6.md
    - 16.7. 最大数值: lcci/16.7.md
    - 16.8. 整数的英语表示: lcci/16.8.md
    - 16.9. 运算: lcci/16.9.md
    - 16.10. 生存人数: lcci/16.10.md
    - 16.11. 跳水板: lcci/16.11.md
    - 16.13. 平分正方形: lcci/16.13.md
    - 16.14. 最佳直线: lcci/16.14.md
    - 16.15. 珠玑妙算: lcci/16.15.md
    - 16.16. 部分排序: lcci/16.16.md
    - 16.17. 连续数列: lcci/16.17.md
    - 16.18. 模式匹配: lcci/16.18.md
    - 16.19. 水域大小: lcci/16.19.md
    - 16.20. T9 键盘: lcci/16.20.md
    - 16.21. 交换和: lcci/16.21.md
    - 16.22. 兰顿蚂蚁: lcci/16.22.md
    - 16.24. 数对和: lcci/16.24.md
    - 16.25. LRU 缓存: lcci/16.25.md
    - 16.26. 计算器: lcci/16.26.md
    - 17.1. 不用加号的加法: lcci/17.1.md
    - 17.4. 消失的数字: lcci/17.4.md
    - 17.5. 字母与数字: lcci/17.5.md
    - 17.6. 2 出现的次数: lcci/17.6.md
    - 17.7. 婴儿名字: lcci/17.7.md
    - 17.8. 马戏团人塔: lcci/17.8.md
    - 17.9. 第 k 个数: lcci/17.9.md
    - 17.10. 主要元素: lcci/17.10.md
    - 17.11. 单词距离: lcci/17.11.md
    - 17.12. BiNode: lcci/17.12.md
    - 17.13. 恢复空格: lcci/17.13.md
    - 17.14. 最小 K 个数: lcci/17.14.md
    - 17.15. 最长单词: lcci/17.15.md
    - 17.16. 按摩师: lcci/17.16.md
    - 17.17. 多次搜索: lcci/17.17.md
    - 17.18. 最短超串: lcci/17.18.md
    - 17.19. 消失的两个数字: lcci/17.19.md
    - 17.20. 连续中值: lcci/17.20.md
    - 17.21. 直方图的水量: lcci/17.21.md
    - 17.22. 单词转换: lcci/17.22.md
    - 17.23. 最大黑方阵: lcci/17.23.md
    - 17.24. 最大子矩阵: lcci/17.24.md
    - 17.25. 单词矩阵: lcci/17.25.md
    - 17.26. 稀疏相似度: lcci/17.26.md

  - 专项训练: tags.md